### ISSUE TITLE
_handle_error

### ISSUE THREAD

**Issue by think-TL** [lawlite19/PythonCrawler-Scrapy-Mysql-File-Template#1]
_handle_error   没办法调用。。

**Comment by lawlite19** [comment]
我这里可以执行啊
![vi_ c 3f go5co8svbhjo11](https://cloud.githubusercontent.com/assets/14356062/23824686/dce17e96-06b5-11e7-8d0a-c4c118189ce2.png)
![x 1y uh4sculc i05m j h](https://cloud.githubusercontent.com/assets/14356062/23824710/5785ad8e-06b6-11e7-9fcf-0089b2c488a0.png)
